version: '3.8'
services:
  login-window:
    image: php:8.0-apache
    volumes:
      - ./login_window/public:/var/www/html/
    ports:
      - 8081:80
  administration:
    image: php:8.0-apache
    volumes:
      - ./administration/fjdcs-admin/public:/var/www/html/
    ports:
      - 8082:80
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
        - ./db/init.sql:/data/application/init.sql