version: '3.8'
services:
  login-window:
    image: httpd:2.4
    volumes:
      - ./login_window/dist/:/usr/local/apache2/htdocs/
    ports:
      - 8081:80
  administration:
    image: httpd:2.4
    volumes:
      - ./administration/fjdcs-admin/dist/:/usr/local/apache2/htdocs/
    ports:
      - 8082:80
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./db/init.sql:/data/application/init.sql
    networks:
      - dbconn
  server:
    container_name: server
    image: openjdk:11
    restart: always
    depends_on:
    - db
    ports:
      - 8080:8080
    volumes:
    - ./server/target:/usr/src/server
    command: bash -c "java -jar /usr/src/server/fujin_domains-1.0.0.jar"
    networks:
      - dbconn
networks:
  dbconn:
    external: true
    name: dbnetwork
